# HTTP
quarkus.http.port=8081

# Datasource commune
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=bank
quarkus.datasource.password=bank

# Dev local
%dev.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/banksimulator
%dev.quarkus.hibernate-orm.schema-management.strategy=update
%dev.quarkus.devservices.enabled=false

# Production / Docker
%prod.quarkus.datasource.jdbc.url=jdbc:postgresql://banksimulator-db:5432/banksimulator
%prod.quarkus.hibernate-orm.schema-management.strategy=validate